import assert from 'node:assert/strict'; import fs from 'node:fs'; import test from 'node:test';
const source=fs.readFileSync(new URL('../dashboard/inventory/order.html',import.meta.url),'utf8');
test('inventory order exposes save and load actions before request order',()=>{const top=source.slice(source.indexOf('id="btn-save-order"'),source.indexOf('id="btn-all-supplier-orders"'));assert.match(top,/Save Order/);assert.match(top,/Load Order/);});
test('Load Order waits for a valid company UUID context',()=>{assert.match(source,/id="btn-load-order"[^>]*disabled>Load Order/);assert.match(source,/if\(!companyId\|\|companyId==='null'\)/);assert.match(source,/document\.getElementById\('btn-load-order'\)\.disabled = false;/);});
test('Save Order is visually removed when the draft is empty',()=>{assert.match(source,/#btn-save-order\[hidden\]\s*\{\s*display:none;/);assert.match(source,/saveButton\.hidden = !hasOrders/);});
test('saved orders persist company-scoped SKU quantities',()=>{assert.match(source,/key:'inventory_saved_orders'/);assert.match(source,/company_id:companyId/);assert.match(source,/items: getPanelOrderItems\(panel\)/);assert.match(source,/Order Name/);assert.match(source,/Saved Order/);});
test('load modal can delete saves and order modals use X close buttons',()=>{assert.match(source,/id="delete-saved-order"[^>]*>Delete<\/button>[\s\S]*?>Cancel<\/button>/);assert.equal((source.match(/class="saved-order-close"/g)||[]).length,2);assert.match(source,/deleteSelectedSavedOrder = async function\(button\)[\s\S]*?savedOrders\.filter\(order=>order\.id!==selected\.order\.id\)/);});
test('Load Order includes editable requested orders and preserves their request ID',()=>{assert.doesNotMatch(source,/btn-pending-orders/);assert.match(source,/Requested: \$\{order\.reference_id\}/);assert.match(source,/options\.sort\(\(a,b\)=>Date\.parse\(b\.savedAt\|\|0\)-Date\.parse\(a\.savedAt\|\|0\)\)/);assert.match(source,/\.eq\('type','supplier_order'\)\.eq\('status','ordered'\)/);assert.match(source,/state\.requestReference=selected\.kind==='requested'\?order\.reference_id:''/);assert.match(source,/const refOrder = state\.requestReference \|\|/);assert.match(source,/update\(\{quantity:itemBySku\.get\(row\.sku\)\.qty\}\)/);});
test('loaded requested orders change the primary action to Overwrite Order',()=>{assert.match(source,/const isOverwrite = panels\.some\(panel => Boolean\(getReorderState\(panel\)\.requestReference\)\)/);assert.match(source,/button\.textContent = isOverwrite \? 'Overwrite Order' : 'Request Order'/);});
