'use strict';
const OBJECTIONS=['Price','Schedule','Payment Process','Location','Others'],COLS=26;
const S={sb:null,companyId:null,customers:[],employees:[],products:[],editing:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const money=v=>`₱${(Number(v||0)/100).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function date(v){if(!v)return'—';const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'})}
function toast(msg,error=false){const e=document.createElement('div');e.className=`toast${error?' error':''}`;e.textContent=msg;$('toast-container').appendChild(e);setTimeout(()=>e.remove(),3500)}
function empName(id){const e=S.employees.find(x=>x.id===id);return e?[e.first_name,e.last_name].filter(Boolean).join(' '):'Unassigned'}
const chips=a=>(a||[]).length?a.map(v=>`<span class="chip">${esc(v)}</span>`).join(''):'—';
function links(a,label){return Array.isArray(a)&&a.length?a.map((u,i)=>`<a class="media" href="${esc(u)}" target="_blank" rel="noopener">${esc(label)} ${i+1}</a>`).join(''):'—'}
function parseLines(v){return String(v||'').split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const[a,b,c]=x.split('|').map(y=>y.trim());return{sku:a||'Item',price:Math.max(0,Math.round((Number(b)||0)*100)),quantity:Math.max(1,Math.round(Number(c)||1))}})}
const lines=a=>(a||[]).map(x=>`${x.sku||'Item'} | ${(Number(x.price||0)/100).toFixed(2)} | ${x.quantity||1}`).join('\n');
const sum=a=>(a||[]).reduce((n,x)=>n+Number(x.price||0)*Number(x.quantity||1),0);
function stats(){const c=S.customers;$('s-total').textContent=c.length;$('s-inquiry').textContent=c.filter(x=>x.stage==='Inquiry').length;$('s-scheduled').textContent=c.filter(x=>x.stage==='Scheduled').length;$('s-installed').textContent=c.filter(x=>x.stage==='Installed').length;$('s-ltv').textContent=money(c.reduce((n,x)=>n+Number(x.lifetime_value||0),0))}
function render(){
 const q=$('search').value.toLowerCase().trim(),st=$('stage-filter').value,so=$('source-filter').value;
 const list=S.customers.filter(c=>{const hay=[c.first_name,c.last_name,c.social_handle,c.email,c.contact_number,c.address,c.source,c.stage,empName(c.assigned_employee_id),...(c.objections||[]),...(c.recommendation_skus||[])].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!st||c.stage===st)&&(!so||c.source===so)});
 $('count').textContent=`${list.length} customer${list.length===1?'':'s'}`;
 if(!list.length){$('rows').innerHTML=`<tr><td colspan="${COLS}" style="text-align:center;padding:3rem;color:var(--text-muted)">No customers match the current filters.</td></tr><tr class="spacer"><td colspan="${COLS}"></td></tr>`;return}
 $('rows').innerHTML=list.map(c=>`<tr><td>${esc(c.first_name)}</td><td>${esc(c.last_name)}</td><td>${esc(c.social_handle||'—')}</td><td>${esc(c.email||'—')}</td><td>${esc(c.contact_number||'—')}</td><td class="wrap">${esc(c.address||'—')}</td><td>${links(c.document_urls,'Document')}</td><td class="wrap">${esc(c.notes||'—')}</td><td>${esc(c.source||'—')}</td><td>${esc(empName(c.assigned_employee_id))}</td><td class="wrap">${chips(c.objections)}</td><td class="wrap">${chips(c.recommendation_skus)}</td><td>${chips([c.stage])}</td><td>${links(c.door_image_urls,'Image')}</td><td>${esc(c.door_rating||'—')}</td><td>${date(c.last_customer_response_date)}</td><td>${date(c.followup_date)}</td><td class="wrap">${chips((c.purchase_items||[]).map(x=>`${x.sku}: ${money(x.price)} × ${x.quantity||1}`))}</td><td class="wrap">${chips((c.additional_items||[]).map(x=>`${x.sku}: ${money(x.price)}`))}</td><td class="wrap">${chips((c.less_items||[]).map(x=>`${x.sku}: -${money(x.price)}`))}</td><td><b>${money(c.purchase_total)}</b></td><td>${links(c.deposit_image_urls,'Deposit')}</td><td>${links(c.receipt_ar_urls,'AR')}</td><td>${links(c.full_payment_image_urls,'Payment')}</td><td><b>${money(c.lifetime_value)}</b></td><td><button class="icon" onclick="CRM.edit('${esc(c.id)}')" title="Edit"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z"/></svg></button></td></tr>`).join('')+`<tr class="spacer"><td colspan="${COLS}"></td></tr>`;
}
function selectors(r){
 const inactive=r?.assigned_employee_id?S.employees.find(e=>e.id===r.assigned_employee_id&&e.employment_status!=='Active'):null;
 $('assigned').innerHTML='<option value="">Unassigned</option>'+(inactive?`<option value="${esc(inactive.id)}">${esc(empName(inactive.id))} (Inactive)</option>`:'')+S.employees.filter(e=>e.employment_status==='Active').sort((a,b)=>empName(a.id).localeCompare(empName(b.id))).map(e=>`<option value="${esc(e.id)}">${esc(empName(e.id))}</option>`).join('');
 $('recommendations').innerHTML=S.products.sort((a,b)=>String(a.sku).localeCompare(String(b.sku))).map(p=>`<option value="${esc(p.sku)}">${esc(p.sku)} — ${esc(p.title||'')}</option>`).join('');
 $('objections').innerHTML=OBJECTIONS.map(o=>`<label><input type="checkbox" value="${esc(o)}"> ${esc(o)}</label>`).join('');
}
function setMulti(select,values){const s=new Set(values||[]);Array.from(select.options).forEach(o=>{o.selected=s.has(o.value)})}
function open(r=null){
 S.editing=r;selectors(r);$('form').reset();$('modal-title').textContent=r?'Edit Customer':'New Customer';$('record-id').value=r?.id||'';$('first-name').value=r?.first_name||'';$('last-name').value=r?.last_name||'';$('social').value=r?.social_handle||'';$('email').value=r?.email||'';$('contact').value=r?.contact_number||'';$('address').value=r?.address||'';$('notes').value=r?.notes||'';$('source').value=r?.source||'';$('assigned').value=r?.assigned_employee_id||'';$('stage').value=r?.stage||'Inquiry';$('door-rating').value=r?.door_rating||'';$('last-response').value=r?.last_customer_response_date||'';$('followup').value=r?.followup_date||'';$('purchases').value=lines(r?.purchase_items);$('additional').value=lines(r?.additional_items);$('less').value=lines(r?.less_items);$('ltv').value=r?(Number(r.lifetime_value||0)/100).toFixed(2):'';setMulti($('recommendations'),r?.recommendation_skus);document.querySelectorAll('#objections input').forEach(i=>{i.checked=(r?.objections||[]).includes(i.value)});const m=$('modal');m.style.display='flex';m.offsetHeight;m.classList.add('open');m.setAttribute('aria-hidden','false')
}
function close(){const m=$('modal');m.classList.remove('open');m.setAttribute('aria-hidden','true');setTimeout(()=>{if(!m.classList.contains('open'))m.style.display='none'},150)}
async function upload(files,category){const out=[];for(const f of Array.from(files||[])){const b64=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)});const res=await BKAuth.authenticatedFetch('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileBase64:b64,fileName:`crm_${Date.now()}_${f.name}`,category,refId:S.editing?.id||'new-customer',type:'crm',companyId:S.companyId})});if(!res.ok)throw new Error('upload');out.push((await res.json()).url)}return out}
async function save(e){
 e.preventDefault();const btn=$('save');btn.disabled=true;btn.textContent='Saving…';
 try{
  const old=S.editing||{},door=$('door-images').files;if((old.door_image_urls||[]).length+door.length>5){toast('Door images are limited to five.',true);return}
  const [docs,doors,deps,recs,pays]=await Promise.all([upload($('documents').files,'crm-documents'),upload(door,'crm-door-images'),upload($('deposits').files,'crm-deposits'),upload($('receipts').files,'crm-receipts'),upload($('payments').files,'crm-payments')]);
  const p=parseLines($('purchases').value),a=parseLines($('additional').value),l=parseLines($('less').value);
  const payload={company_id:S.companyId,first_name:$('first-name').value.trim(),last_name:$('last-name').value.trim(),social_handle:$('social').value.trim()||null,email:$('email').value.trim()||null,contact_number:$('contact').value.trim()||null,address:$('address').value.trim()||null,notes:$('notes').value.trim()||null,source:$('source').value||null,assigned_employee_id:$('assigned').value||null,objections:Array.from(document.querySelectorAll('#objections input:checked')).map(i=>i.value),recommendation_skus:Array.from($('recommendations').selectedOptions).map(o=>o.value),stage:$('stage').value,door_rating:$('door-rating').value||null,last_customer_response_date:$('last-response').value||null,followup_date:$('followup').value||null,purchase_items:p,additional_items:a,less_items:l,purchase_total:Math.max(0,sum(p)+sum(a)-sum(l)),lifetime_value:Math.max(0,Math.round((Number($('ltv').value)||0)*100)),document_urls:[...(old.document_urls||[]),...docs],door_image_urls:[...(old.door_image_urls||[]),...doors],deposit_image_urls:[...(old.deposit_image_urls||[]),...deps],receipt_ar_urls:[...(old.receipt_ar_urls||[]),...recs],full_payment_image_urls:[...(old.full_payment_image_urls||[]),...pays]};
  const id=$('record-id').value,req=id?S.sb.from('crm_customers').update(payload).eq('id',id).eq('company_id',S.companyId):S.sb.from('crm_customers').insert(payload);const{error}=await req;if(error)throw error;close();toast(id?'Customer updated.':'Customer created.');await load();
 }catch(err){console.error(err);toast('Customer could not be saved. Check required fields and attachments.',true)}finally{btn.disabled=false;btn.textContent='Save Customer'}
}
async function load(){ $('rows').innerHTML=`<tr><td colspan="${COLS}"><div class="loading"><i></i>Loading customers…</div></td></tr>`;const{data,error}=await S.sb.from('crm_customers').select('id,company_id,first_name,last_name,social_handle,email,contact_number,address,document_urls,notes,source,assigned_employee_id,objections,recommendation_skus,stage,door_image_urls,door_rating,last_customer_response_date,followup_date,purchase_items,additional_items,less_items,purchase_total,deposit_image_urls,receipt_ar_urls,full_payment_image_urls,lifetime_value,updated_at').eq('company_id',S.companyId).order('updated_at',{ascending:false}).limit(500);if(error)throw error;S.customers=data||[];stats();render()}
async function init(){try{const auth=await BKAuth.checkRoleGate(['Sales'],'/admin.html');if(!auth)return;S.sb=BKAuth.sb;const{data:co,error:ce}=await S.sb.from('companies').select('id').eq('tenant_id',auth.tenantId).limit(1).maybeSingle();if(ce||!co?.id)throw ce||new Error('company');S.companyId=co.id;const[e,p]=await Promise.all([S.sb.from('employees').select('id,first_name,last_name,employment_status').eq('company_id',S.companyId).limit(500),S.sb.from('products').select('id,sku,title,status').eq('company_id',S.companyId).order('sku').limit(500)]);if(e.error||p.error)throw e.error||p.error;S.employees=e.data||[];S.products=p.data||[];await load();$('new-customer').onclick=()=>open();$('close').onclick=close;$('cancel').onclick=close;$('form').onsubmit=save;$('refresh').onclick=()=>load().catch(fail);$('search').oninput=render;$('stage-filter').onchange=render;$('source-filter').onchange=render;$('modal').onclick=e=>{if(e.target.id==='modal')close()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('modal').classList.contains('open'))close()})}catch(e){fail(e)}}
function fail(e){console.error(e);$('rows').innerHTML=`<tr><td colspan="${COLS}" style="text-align:center;padding:3rem;color:var(--danger)">The CRM customer list could not be loaded.</td></tr>`;toast('CRM data could not be loaded.',true)}
window.CRM={edit(id){const r=S.customers.find(x=>x.id===id);if(r)open(r)}};document.addEventListener('DOMContentLoaded',init);
