-- Add an isolated, auditable moving-average cost layer for COGS reporting.
-- Operational inventory statuses and quantity counters remain unchanged.

ALTER TABLE public.inventory
  ADD COLUMN IF NOT EXISTS average_unit_cost_centavos BIGINT NOT NULL DEFAULT 0;

ALTER TABLE public.inventory_transactions
  ADD COLUMN IF NOT EXISTS ordered_unit_cost_centavos BIGINT,
  ADD COLUMN IF NOT EXISTS received_unit_cost_centavos BIGINT;

CREATE TABLE IF NOT EXISTS public.inventory_cost_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  warehouse_id UUID REFERENCES public.warehouses(id) ON DELETE SET NULL,
  inventory_transaction_id UUID NOT NULL REFERENCES public.inventory_transactions(id) ON DELETE CASCADE,
  reference_id TEXT,
  sku TEXT NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('cogs', 'cogs_reversal')),
  quantity INTEGER NOT NULL,
  unit_cost_centavos BIGINT NOT NULL DEFAULT 0,
  total_cost_centavos BIGINT NOT NULL DEFAULT 0,
  cost_method TEXT NOT NULL CHECK (cost_method IN ('moving_average', 'legacy_estimate', 'catalog_fallback', 'missing_cost')),
  recognized_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (inventory_transaction_id, event_type)
);

ALTER TABLE public.inventory_cost_ledger ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'inventory_cost_ledger'
      AND policyname = 'Finance module inventory cost ledger'
  ) THEN
    CREATE POLICY "Finance module inventory cost ledger"
      ON public.inventory_cost_ledger
      FOR SELECT
      USING (public.has_module_access((SELECT auth.uid()), company_id, 'Finance'));
  END IF;
END;
$$;

REVOKE ALL ON public.inventory_cost_ledger FROM PUBLIC;
REVOKE INSERT, UPDATE, DELETE ON public.inventory_cost_ledger FROM authenticated;
GRANT SELECT ON public.inventory_cost_ledger TO authenticated, service_role;
GRANT ALL ON public.inventory_cost_ledger TO service_role;

CREATE INDEX IF NOT EXISTS idx_inventory_cost_ledger_company_recognized
  ON public.inventory_cost_ledger (company_id, recognized_at DESC);

CREATE INDEX IF NOT EXISTS idx_inventory_cost_ledger_company_sku_recognized
  ON public.inventory_cost_ledger (company_id, sku, recognized_at DESC);

CREATE OR REPLACE FUNCTION public.capture_inventory_order_cost()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  resolved_company_id UUID;
BEGIN
  IF NEW.type <> 'supplier_order' OR NEW.ordered_unit_cost_centavos IS NOT NULL THEN
    RETURN NEW;
  END IF;

  resolved_company_id := NEW.company_id;
  IF resolved_company_id IS NULL AND NEW.warehouse_id IS NOT NULL THEN
    SELECT company.id
    INTO resolved_company_id
    FROM public.warehouses AS warehouse
    JOIN public.companies AS company ON company.tenant_id = warehouse.tenant_id
    WHERE warehouse.id = NEW.warehouse_id
    LIMIT 1;
  END IF;

  SELECT product.dealer_price
  INTO NEW.ordered_unit_cost_centavos
  FROM public.products AS product
  WHERE lower(product.sku) = lower(NEW.sku)
    AND (product.company_id = resolved_company_id OR product.company_id IS NULL)
  ORDER BY (product.company_id = resolved_company_id) DESC, product.updated_at DESC NULLS LAST
  LIMIT 1;

  NEW.ordered_unit_cost_centavos := COALESCE(NEW.ordered_unit_cost_centavos, 0);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_capture_inventory_order_cost
  ON public.inventory_transactions;

CREATE TRIGGER trg_capture_inventory_order_cost
BEFORE INSERT OR UPDATE OF status
ON public.inventory_transactions
FOR EACH ROW
EXECUTE FUNCTION public.capture_inventory_order_cost();

CREATE OR REPLACE FUNCTION public.record_inventory_cost_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_quantity BIGINT := 0;
  current_average BIGINT := 0;
  effective_unit_cost BIGINT := 0;
  effective_method TEXT := 'missing_cost';
  event_timestamp TIMESTAMPTZ;
BEGIN
  IF NEW.company_id IS NULL OR NEW.warehouse_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF NEW.type = 'supplier_order'
    AND NEW.status = 'received'
    AND OLD.status IS DISTINCT FROM 'received'
  THEN
    effective_unit_cost := COALESCE(
      NEW.received_unit_cost_centavos,
      NEW.ordered_unit_cost_centavos,
      0
    );

    SELECT inventory.available, inventory.average_unit_cost_centavos
    INTO current_quantity, current_average
    FROM public.inventory AS inventory
    WHERE inventory.company_id = NEW.company_id
      AND inventory.warehouse_id = NEW.warehouse_id
      AND lower(inventory.sku) = lower(NEW.sku)
    FOR UPDATE;

    IF FOUND AND NEW.quantity > 0 AND effective_unit_cost >= 0 THEN
      UPDATE public.inventory AS inventory
      SET average_unit_cost_centavos = CASE
            WHEN GREATEST(current_quantity, 0) + NEW.quantity > 0 THEN
              ROUND((GREATEST(current_quantity, 0) * current_average + NEW.quantity * effective_unit_cost)::NUMERIC
                / (GREATEST(current_quantity, 0) + NEW.quantity))::BIGINT
            ELSE effective_unit_cost
          END,
          updated_at = NOW()
      WHERE inventory.company_id = NEW.company_id
        AND inventory.warehouse_id = NEW.warehouse_id
        AND lower(inventory.sku) = lower(NEW.sku);
    END IF;

    RETURN NEW;
  END IF;

  IF NEW.type = 'customer_order'
    AND NEW.status = 'received'
    AND OLD.status IS DISTINCT FROM 'received'
  THEN
    SELECT inventory.average_unit_cost_centavos
    INTO effective_unit_cost
    FROM public.inventory AS inventory
    WHERE inventory.company_id = NEW.company_id
      AND inventory.warehouse_id = NEW.warehouse_id
      AND lower(inventory.sku) = lower(NEW.sku)
    LIMIT 1;

    IF COALESCE(effective_unit_cost, 0) > 0 THEN
      effective_method := 'moving_average';
    ELSE
      SELECT product.dealer_price
      INTO effective_unit_cost
      FROM public.products AS product
      WHERE lower(product.sku) = lower(NEW.sku)
        AND (product.company_id = NEW.company_id OR product.company_id IS NULL)
      ORDER BY (product.company_id = NEW.company_id) DESC, product.updated_at DESC NULLS LAST
      LIMIT 1;

      IF COALESCE(effective_unit_cost, 0) > 0 THEN
        effective_method := 'catalog_fallback';
      ELSE
        effective_method := 'missing_cost';
      END IF;
    END IF;

    effective_unit_cost := COALESCE(effective_unit_cost, 0);
    event_timestamp := COALESCE(NEW.timestamp_received, NOW());

    INSERT INTO public.inventory_cost_ledger (
      company_id,
      warehouse_id,
      inventory_transaction_id,
      reference_id,
      sku,
      event_type,
      quantity,
      unit_cost_centavos,
      total_cost_centavos,
      cost_method,
      recognized_at
    ) VALUES (
      NEW.company_id,
      NEW.warehouse_id,
      NEW.id,
      NEW.reference_id,
      upper(NEW.sku),
      'cogs',
      NEW.quantity,
      effective_unit_cost,
      NEW.quantity * effective_unit_cost,
      effective_method,
      event_timestamp
    )
    ON CONFLICT (inventory_transaction_id, event_type) DO NOTHING;

    RETURN NEW;
  END IF;

  IF NEW.type = 'customer_order'
    AND NEW.status = 'returned'
    AND OLD.status IS DISTINCT FROM 'returned'
  THEN
    SELECT ledger.unit_cost_centavos
    INTO effective_unit_cost
    FROM public.inventory_cost_ledger AS ledger
    WHERE ledger.inventory_transaction_id = NEW.id
      AND ledger.event_type = 'cogs'
    LIMIT 1;

    effective_unit_cost := COALESCE(effective_unit_cost, 0);
    effective_method := CASE WHEN effective_unit_cost > 0 THEN 'moving_average' ELSE 'missing_cost' END;
    event_timestamp := COALESCE(NEW.timestamp_returned, NOW());

    INSERT INTO public.inventory_cost_ledger (
      company_id,
      warehouse_id,
      inventory_transaction_id,
      reference_id,
      sku,
      event_type,
      quantity,
      unit_cost_centavos,
      total_cost_centavos,
      cost_method,
      recognized_at
    ) VALUES (
      NEW.company_id,
      NEW.warehouse_id,
      NEW.id,
      NEW.reference_id,
      upper(NEW.sku),
      'cogs_reversal',
      -NEW.quantity,
      effective_unit_cost,
      -(NEW.quantity * effective_unit_cost),
      effective_method,
      event_timestamp
    )
    ON CONFLICT (inventory_transaction_id, event_type) DO NOTHING;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_record_inventory_cost_event
  ON public.inventory_transactions;

CREATE TRIGGER trg_record_inventory_cost_event
AFTER UPDATE OF status
ON public.inventory_transactions
FOR EACH ROW
EXECUTE FUNCTION public.record_inventory_cost_event();

REVOKE ALL ON FUNCTION public.capture_inventory_order_cost() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.record_inventory_cost_event() FROM PUBLIC;

-- Seed current inventory carrying costs without changing quantities or statuses.
UPDATE public.inventory AS inventory
SET average_unit_cost_centavos = COALESCE((
      SELECT product.dealer_price
      FROM public.products AS product
      WHERE lower(product.sku) = lower(inventory.sku)
        AND (product.company_id = inventory.company_id OR product.company_id IS NULL)
      ORDER BY (product.company_id = inventory.company_id) DESC, product.updated_at DESC NULLS LAST
      LIMIT 1
    ), 0),
    updated_at = NOW()
WHERE inventory.average_unit_cost_centavos = 0;

-- Preserve historical reporting with explicitly labeled estimated costs.
INSERT INTO public.inventory_cost_ledger (
  company_id,
  warehouse_id,
  inventory_transaction_id,
  reference_id,
  sku,
  event_type,
  quantity,
  unit_cost_centavos,
  total_cost_centavos,
  cost_method,
  recognized_at
)
SELECT
  transaction.company_id,
  transaction.warehouse_id,
  transaction.id,
  transaction.reference_id,
  upper(transaction.sku),
  'cogs',
  transaction.quantity,
  COALESCE(historical.cost, product.dealer_price, 0),
  transaction.quantity * COALESCE(historical.cost, product.dealer_price, 0),
  CASE
    WHEN COALESCE(historical.cost, product.dealer_price, 0) > 0 THEN 'legacy_estimate'
    ELSE 'missing_cost'
  END,
  COALESCE(transaction.timestamp_received, transaction.updated_at, transaction.created_at)
FROM public.inventory_transactions AS transaction
LEFT JOIN LATERAL (
  SELECT history.cost
  FROM public.product_cost_history AS history
  WHERE history.company_id = transaction.company_id
    AND lower(history.sku) = lower(transaction.sku)
    AND history.start_date <= COALESCE(transaction.timestamp_received, transaction.updated_at, transaction.created_at)
    AND (history.end_date IS NULL OR history.end_date >= COALESCE(transaction.timestamp_received, transaction.updated_at, transaction.created_at))
  ORDER BY history.start_date DESC, history.id DESC
  LIMIT 1
) AS historical ON TRUE
LEFT JOIN LATERAL (
  SELECT catalog.dealer_price
  FROM public.products AS catalog
  WHERE lower(catalog.sku) = lower(transaction.sku)
    AND (catalog.company_id = transaction.company_id OR catalog.company_id IS NULL)
  ORDER BY (catalog.company_id = transaction.company_id) DESC, catalog.updated_at DESC NULLS LAST
  LIMIT 1
) AS product ON TRUE
WHERE transaction.type = 'customer_order'
  AND transaction.status IN ('received', 'returned')
  AND transaction.company_id IS NOT NULL
  AND transaction.warehouse_id IS NOT NULL
ON CONFLICT (inventory_transaction_id, event_type) DO NOTHING;

UPDATE public.inventory_cost_ledger
SET cost_method = 'missing_cost'
WHERE cost_method = 'legacy_estimate'
  AND unit_cost_centavos = 0;

INSERT INTO public.inventory_cost_ledger (
  company_id,
  warehouse_id,
  inventory_transaction_id,
  reference_id,
  sku,
  event_type,
  quantity,
  unit_cost_centavos,
  total_cost_centavos,
  cost_method,
  recognized_at
)
SELECT
  transaction.company_id,
  transaction.warehouse_id,
  transaction.id,
  transaction.reference_id,
  upper(transaction.sku),
  'cogs_reversal',
  -transaction.quantity,
  original.unit_cost_centavos,
  -(transaction.quantity * original.unit_cost_centavos),
  'legacy_estimate',
  COALESCE(transaction.timestamp_returned, transaction.updated_at, transaction.created_at)
FROM public.inventory_transactions AS transaction
JOIN public.inventory_cost_ledger AS original
  ON original.inventory_transaction_id = transaction.id
 AND original.event_type = 'cogs'
WHERE transaction.type = 'customer_order'
  AND transaction.status = 'returned'
  AND transaction.company_id IS NOT NULL
ON CONFLICT (inventory_transaction_id, event_type) DO NOTHING;
